CREATE TABLE authuser (
  id            BIGINT        NOT NULL AUTO_INCREMENT,
  user_name     VARCHAR(255)  NOT NULL,
  name          VARCHAR(255)  NOT NULL,
  create_date   TIMESTAMP      NOT NULL DEFAULT '0000-00-00 00:00:00',
  update_date   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;