version: '3'
services:
  finance:
    image: "nginx:1.16.1"
    container_name: "finance"
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/source_code
    links:
      - finance-mysql:mysql
  finance-mysql:
    image: "mysql:5.5.60"
    container_name: "mysql-finance"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: finance
      MYSQL_USER: yxf
      MYSQL_PASSWORD: finance
    ports:
      - "3308:3306"
    volumes:
      - ./docker/tmp_data/mysql:/var/lib/mysql
      # - ./docker/tmp_logs/mysql:/var/log/mysql
      # - ./docker/tmp_conf/mysql:/etc/mysql